---
platform: linux

image_resource:
  type: docker-image
  source: {repository: springio/java-cache-resource}

inputs:
- name: git-repo
- name: java-cache

run:
  path: git-repo/samples/scripts/build.sh
