resource_types:
  - name: java-cache-resource
    type: docker-image
    source: {repository: springio/java-cache-resource, tag: latest}
resources:
  - name: git-repo
    type: git
    source: &repo-source
      uri: https://github.com/philwebb/java-cache-resource.git
  - name: java-cache
    type: java-cache-resource
    source:
      <<: *repo-source
      paths:
        - "**pom.xml"
      depth: 1
      folders:
        - source: ~/.m2
          destination: m2
      commands:
        - "./samples/maven/mvnw -f ./samples/maven.pom.xml dependency:go-offline"
jobs:
  - name: build
    plan:
      - get: java-cache
      - get: git-repo
        trigger: true
      - task: build
        file: git-repo/samples/maven/ci/tasks/build.yml
