resource_types:
  - name: java-cache-resource
    type: docker-image
    source: {repository: springio/java-cache-resource, tag: latest}
resources:
  - name: git-repo
    type: git
    source: &repo-source
      uri: https://github.com/philwebb/java-cache-resource.git
  - name: java-cache
    type: java-cache-resource
    source:
      <<: *repo-source
      paths:
        - "**build.gradle"
      depth: 1
      folders:
        - source: ~/.gradle
          destination: gradle
      commands:
        - "(cd ./samples/gradle && ./gradlew --project-cache-dir ~/.gradle/project build)"
      cleanup:
        - ".*SNAPSHOT"
jobs:
  - name: gradle-build
    plan:
      - get: java-cache
      - get: git-repo
        trigger: true
      - task: build
        file: git-repo/samples/gradle/ci/tasks/build.yml
