resource_types:
  - name: java-cache-resource
    type: docker-image
    source: {repository: springio/java-cache-resource, tag: latest}
resources:
  - name: git-repo
    type: git
    source: &repo-source
      uri: https://github.com/philwebb/java-cache-resource.git
      branch: maven-restruct
  - name: maven-repo-cache
    type: maven-cache-resource
    source:
      <<: *repo-source
      depth: 1
      commands:
        - "./mvnw -Dfast -DskipTests install dependency:go-offline"
        - "./mvnw -f spring-boot-samples/pom.xml dependency:go-offline"
      purge:
        - org.springframework.boot
jobs:
  - name: cache
    plan:
      - get: git-repo
        trigger: true
      - get: maven-repo-cache
  - name: build
    plan:
      - get: git-repo
        trigger: true
        passed: [cache]
      - get: maven-repo-cache
        passed: [cache]
      - task: run-build
        file: spring-boot/ci/tasks/run-build.yml
