resource_types:
  - name: java-cache-resource
    type: docker-image
    source: {repository: springio/java-cache-resource, tag: latest}
resources:
  - name: git-repo
    type: git
    source: &repo-source
      uri: https://github.com/philwebb/java-cache-resource.git
  - name: java-cache
    type: java-cache-resource
    source:
      <<: *repo-source
      depth: 1
      folders:
        - source: ~/.javabuild
          destination: javabuild
      commands:
        - "echo 'foo' > ~/.javabuild/test"
jobs:
  - name: simple-build
    plan:
      - get: java-cache
      - get: git-repo
        trigger: true
      - task: build
        file: git-repo/samples/simple/ci/tasks/build.yml
