resources:
  - name: java-cache-resource
    type: git
    source:
      uri: https://github.com/spring-io/java-cache-resource.git
jobs:
  - name: build
    plan:
      - get: java-cache-resource
        trigger: true
      - task: test
        file: git-repo/ci/tasks/test.yml
